### ISSUE TITLE
Headers 4.4.132 issue

### ISSUE THREAD

**Issue by 91ajames** [TinkerBoard/debian_kernel#55]
Tried several ways on making this file but end's up shutting down due to the kernal.
Tried 4.4.103+-3 incase if it was a similar issue, but still sees 132 even after deleting and recreating it. nothing.
Any ideas?

docker-compose v2.0
```
   wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=192.168.1.0/24,192.168.2.0/24 #optional
    volumes:
      - /docker/wireguard/config:/config
      - /lib/modules:/lib/modules
#      - /lib/modules/4.4.103+/:/lib/modules/4.4.103+/
#     - /lib/modules/4.4.132+/:/lib/modules/4.4.132+/
    ports:
      - 51820:51820/udp
#    sysctls:
#      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Uname info: Linux 890d79cbe59e 4.4.132+ #1 SMP Tue Oct 23 18:03:49 CST 2018 armv7l armv7l armv7l GNU/Linux
RTNETLINK answers: Operation not supported
**** The wireguard module is not active, will attempt kernel header install and module compilation. ****
**** Attempting kernel header install ****
Get:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease [242 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease [88.7 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease [74.6 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease [88.7 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports bionic/main armhf Packages [1,277 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports bionic/multiverse armhf Packages [157 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports bionic/restricted armhf Packages [12.5 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports bionic/universe armhf Packages [11.0 MB]
Get:9 http://ports.ubuntu.com/ubuntu-ports bionic-updates/restricted armhf Packages [14.5 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main armhf Packages [1,252 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe armhf Packages [1,737 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports bionic-updates/multiverse armhf Packages [7,028 B]
Get:13 http://ports.ubuntu.com/ubuntu-ports bionic-backports/universe armhf Packages [11.0 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports bionic-backports/main armhf Packages [11.2 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports bionic-security/restricted armhf Packages [7,193 B]
Get:16 http://ports.ubuntu.com/ubuntu-ports bionic-security/main armhf Packages [885 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports bionic-security/multiverse armhf Packages [2,424 B]
Get:18 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe armhf Packages [1,064 kB]
Fetched 17.9 MB in 6s (3,049 kB/s)
Reading package lists...
**** No kernel headers found in the Ubuntu or Debian repos!! Will try the headers from host (if mapped), may or may not work ****
**** Kernel headers don't seem to be available, can't compile the module. Sleeping now. . . ****```
